- name: "Documentación de los roles de Azure\_AD"
  href: index.yml
- name: Información general
  items:
    - name: ¿Qué es Azure AD RBAC?
      href: custom-overview.md
- name: Guías de inicio rápido
  items:
    - name: Asignación de roles a usuarios
      href: ../fundamentals/active-directory-users-assign-role-azure-portal.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Conceptos
  items:
    - name: "Descripción de los roles de Azure\_AD"
      href: concept-understand-roles.md
    - name: Comparación de roles
      items:
        - name: Comparación de roles de Azure y Azure AD
          href: ../../role-based-access-control/rbac-and-directory-admin-roles.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
        - name: Roles de Microsoft 365
          href: m365-workload-docs.md
    - name: Asignación de roles basada en grupo
      href: groups-concept.md
    - name: Unidades administrativas
      href: administrative-units.md
    - name: Procedimientos recomendados
      href: best-practices.md
    - name: Seguridad
      items:
        - name: Planeamiento de la seguridad de rol
          href: security-planning.md
        - name: Creación de cuentas de emergencia
          href: security-emergency-access.md
- name: Guías paso a paso
  items:
    - name: Prerrequisitos
      href: prerequisites.md
    - name: Lista de definiciones de roles
      href: role-definitions-list.md
    - name: Lista de asignaciones de roles
      items:
        - name: Lista de asignaciones de roles
          href: view-assignments.md
        - name: Lista de asignaciones de roles para grupos
          href: groups-view-assignments.md
    - name: Asignación de roles
      items:
        - name: Asignación de roles a usuarios
          href: manage-roles-portal.md
        - name: Creación de un grupo al que se pueden asignar roles
          href: groups-create-eligible.md
        - name: Asignación de roles a grupos
          href: groups-assign-role.md
        - name: Hacer que un grupo sea válido para un rol en PIM
          href: groups-pim-eligible.md
        - name: Asignación de roles con ámbito mediante PowerShell
          href: custom-assign-powershell.md
        - name: Asignación de roles mediante Graph API
          href: custom-assign-graph.md
    - name: Eliminación de asignaciones de rol
      items:
        - name: Eliminación de asignaciones de roles de grupos
          href: groups-remove-assignment.md
    - name: Creación de roles personalizados
      items:
        - name: Crear un rol personalizado
          href: custom-create.md
        - name: Creación de roles personalizados para aplicaciones empresariales
          href: custom-enterprise-apps.md
        - name: Creación de registros de aplicaciones ilimitadas
          href: quickstart-app-registration-limits.md
    - name: Unidades administrativas
      items:
        - name: Adición y administración
          href: admin-units-manage.md
        - name: Adición y administración de usuarios
          href: admin-units-add-manage-users.md
        - name: Agregar y administrar grupos
          href: admin-units-add-manage-groups.md
        - name: Asignación de un rol con ámbito
          href: admin-units-assign-roles.md
    - name: Delegado
      items:
        - name: Delegación del rol de administrador de aplicaciones
          href: delegate-app-roles.md
        - name: Delegación de Mi personal
          href: my-staff-configure.md
    - name: Solución de problemas
      items:
        - name: Solución de problemas de roles asignados a grupos
          href: groups-faq-troubleshooting.md
        - name: Solución de problemas de unidades administrativas
          href: admin-units-faq-troubleshoot.md
        - name: Obtener soporte técnico para Azure AD
          href: ../fundamentals/active-directory-troubleshooting-support-howto.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
- name: Referencia
  items:
    - name: Roles integrados
      href: permissions-reference.md
    - name: Roles con privilegios mínimos por tarea
      href: delegate-by-task.md
    - name: Permisos predeterminados de usuario
      href: ../fundamentals/users-default-permissions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: Permisos de roles personalizados
      items:
        - name: Permisos del registro de aplicaciones
          href: custom-available-permissions.md
        - name: Permisos de aplicaciones empresariales
          href: custom-enterprise-app-permissions.md
        - name: Permisos para el consentimiento de aplicaciones
          href: custom-consent-permissions.md
    - name: Límites de servicio de Azure AD
      href: ../enterprise-users/directory-service-limits-restrictions.md?context=%2fazure%2factive-directory%2froles%2fcontext%2fugr-context
    - name: PowerShell de Azure AD
      href: /powershell/module/azuread/#directory-roles
    - name: Microsoft Graph API
      href: /graph/api/resources/directoryrole